name: Submit by PR
on:
  create

jobs:
  create-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Reset current branch
        run: |
          git fetch origin ${{ github.ref }}:${{ github.ref }}
          git reset --hard ${{ github.ref }}

      - name: Create Pull Requestf
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Submission
          title: '[Submission] ${{ github.actor }} '
          labels: submission, automated pr
          assignees: ${{ github.actor }}
          branch: submit/${{ github.actor }}
          body: >
            Assignment submission by ${{ github.actor }}
