name: Test linting

on:
  - push

jobs:
  flake8-test:
    name: flake8 test
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run flake8
      uses: julianwachholz/flake8-action@v2
      with:
        checkName: "flake8 test"
        plugins: flake8-spellcheck
        config: setup.cfg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  pycodestyle-test:
    name: pycodestyle (pep8) test
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
  
    - name: PEP8 test
      uses: quentinguidee/pep8-action@v1
      with:
        args: --exit-code --recursive --in-place --aggressive --aggressive .
