name: Submit test

on:
  - pull_request

jobs:
  submit-test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Reset promotion branch
      run: |
        git fetch origin main:main
        git reset --hard main

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        pip install pytest
        pytest tests
